using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

// Generates committed C# tables for the engine. Usage:
//   dotnet run --project tools/Folio.Gen -- entities [entities.json]
//   dotnet run --project tools/Folio.Gen -- colors [css-color-4.html]
// Without a file, the source is downloaded from the specification.

return args switch
{
    ["entities", ..] => await Entities(args.Length > 1 ? args[1] : null),
    ["colors", ..] => await Colors(args.Length > 1 ? args[1] : null),
    _ => Usage(),
};

static int Usage()
{
    Console.Error.WriteLine("usage: Folio.Gen entities [entities.json] | colors [css-color-4.html]");
    return 2;
}

static async Task<string> Read(string? path, string url) =>
    path is not null ? await File.ReadAllTextAsync(path) : await new HttpClient().GetStringAsync(url);

static async Task<int> Entities(string? path)
{
    var json = await Read(path, "https://html.spec.whatwg.org/entities.json");
    var entries = JsonSerializer.Deserialize<Dictionary<string, Entity>>(json, new JsonSerializerOptions(JsonSerializerDefaults.Web))!
        .Select(e => (Name: e.Key.TrimStart('&'), e.Value.Characters))
        .OrderBy(e => e.Name, StringComparer.Ordinal)
        .ToList();

    var code = new StringBuilder();
    code.Append("""
        // <auto-generated>
        // Generated by tools/Folio.Gen from the named character references table of the HTML standard,
        // https://html.spec.whatwg.org/multipage/named-characters.html. Do not edit.
        // </auto-generated>

        namespace Folio.Html;

        internal static partial class EntityTable
        {
            /// <summary>Reference names without the leading ampersand, in ordinal order.</summary>
            private static readonly string[] Names =
            [

        """);
    foreach (var (name, _) in entries)
        code.Append("        \"").Append(name).Append("\",\n");
    code.Append("""
            ];

            /// <summary>The characters each name in <see cref="Names"/> stands for.</summary>
            private static readonly string[] Values =
            [

        """);
    foreach (var (_, value) in entries)
        code.Append("        \"").Append(Escape(value)).Append("\",\n");
    code.Append("""
            ];
        }

        """);

    await Write(code, "Html", "EntityTable.g.cs", $"{entries.Count} entities");
    return 0;
}

static async Task<int> Colors(string? path)
{
    var html = await Read(path, "https://drafts.csswg.org/css-color-4/");
    var colors = Regex.Matches(html, @"id=""valdef-color-([a-z]+)"">\1</dfn>\s*<td>#([0-9a-f]{6})")
        .Select(m => (Name: m.Groups[1].Value, Hex: m.Groups[2].Value))
        .DistinctBy(c => c.Name)
        .OrderBy(c => c.Name, StringComparer.Ordinal)
        .ToList();
    if (colors.Count < 140)
        throw new InvalidDataException($"Only {colors.Count} named colors found; the specification's markup may have changed.");

    var code = new StringBuilder();
    code.Append("""
        // <auto-generated>
        // Generated by tools/Folio.Gen from the named color table of CSS Color 4,
        // https://drafts.csswg.org/css-color-4/#named-colors. Do not edit.
        // </auto-generated>

        namespace Folio.Css;

        internal static partial class NamedColors
        {
            /// <summary>Opaque named colors as 0xRRGGBB.</summary>
            private static readonly Dictionary<string, int> Table = new(StringComparer.OrdinalIgnoreCase)
            {

        """);
    foreach (var (name, hex) in colors)
        code.Append("        [\"").Append(name).Append("\"] = 0x").Append(hex.ToUpperInvariant()).Append(",\n");
    code.Append("""
            };
        }

        """);

    await Write(code, "Css", "NamedColors.g.cs", $"{colors.Count} named colors");
    return 0;
}

static async Task Write(StringBuilder code, string folder, string file, string summary)
{
    var output = Path.Combine(FindRoot(), "src", "Folio", folder, file);
    await File.WriteAllTextAsync(output, code.ToString().ReplaceLineEndings("\n"));
    Console.WriteLine($"{summary} -> {output}");
}

static string Escape(string value)
{
    var escaped = new StringBuilder();
    foreach (var c in value)
    {
        var printable = c is >= ' ' and <= '~' and not '"' and not '\\';
        escaped.Append(printable ? c.ToString() : "\\u" + ((int)c).ToString("X4", CultureInfo.InvariantCulture));
    }
    return escaped.ToString();
}

static string FindRoot()
{
    for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir is not null; dir = dir.Parent)
    {
        if (File.Exists(Path.Combine(dir.FullName, "Folio.slnx")))
            return dir.FullName;
    }
    throw new DirectoryNotFoundException("Folio.slnx not found.");
}

internal sealed record Entity(string Characters);
