using System.Globalization;
using System.Text;
using System.Text.Json;

// Generates committed C# tables for the engine. Usage:
//   dotnet run --project tools/Folio.Gen -- entities [entities.json]
// Without a file, entities.json is downloaded from the HTML standard.

if (args is not ["entities", ..])
{
    Console.Error.WriteLine("usage: Folio.Gen entities [entities.json]");
    return 2;
}

const string EntitiesUrl = "https://html.spec.whatwg.org/entities.json";
var json = args.Length > 1
    ? await File.ReadAllTextAsync(args[1])
    : await new HttpClient().GetStringAsync(EntitiesUrl);

var entries = JsonSerializer.Deserialize<Dictionary<string, Entity>>(json, new JsonSerializerOptions(JsonSerializerDefaults.Web))!
    .Select(e => (Name: e.Key.TrimStart('&'), e.Value.Characters))
    .OrderBy(e => e.Name, StringComparer.Ordinal)
    .ToList();

var code = new StringBuilder();
code.Append("""
    // <auto-generated>
    // Generated by tools/Folio.Gen from the named character references table of the HTML standard,
    // https://html.spec.whatwg.org/multipage/named-characters.html. Do not edit.
    // </auto-generated>

    namespace Folio.Html;

    internal static partial class EntityTable
    {
        /// <summary>Reference names without the leading ampersand, in ordinal order.</summary>
        private static readonly string[] Names =
        [

    """);
foreach (var (name, _) in entries)
    code.Append("        \"").Append(name).Append("\",\n");
code.Append("""
        ];

        /// <summary>The characters each name in <see cref="Names"/> stands for.</summary>
        private static readonly string[] Values =
        [

    """);
foreach (var (_, value) in entries)
    code.Append("        \"").Append(Escape(value)).Append("\",\n");
code.Append("""
        ];
    }

    """);

var output = Path.Combine(FindRoot(), "src", "Folio", "Html", "EntityTable.g.cs");
await File.WriteAllTextAsync(output, code.ToString().ReplaceLineEndings("\n"));
Console.WriteLine($"{entries.Count} entities -> {output}");
return 0;

static string Escape(string value)
{
    var escaped = new StringBuilder();
    foreach (var c in value)
    {
        var printable = c is >= ' ' and <= '~' and not '"' and not '\\';
        escaped.Append(printable ? c.ToString() : "\\u" + ((int)c).ToString("X4", CultureInfo.InvariantCulture));
    }
    return escaped.ToString();
}

static string FindRoot()
{
    for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir is not null; dir = dir.Parent)
    {
        if (File.Exists(Path.Combine(dir.FullName, "Folio.slnx")))
            return dir.FullName;
    }
    throw new DirectoryNotFoundException("Folio.slnx not found.");
}

internal sealed record Entity(string Characters);
