using System.Globalization;
using System.Security.Cryptography;
using System.Text;

/// <summary>
/// Generates src/Folio/Typography/UnicodeData.g.cs from Unicode Character Database files in a local folder
/// (by default .cache/unicode/&lt;version&gt;), after checking them against the committed checksums.
/// </summary>
internal static class Unicode
{
    public const string Version = "18.0.0";

    public static async Task<int> Generate(string root, string? folder)
    {
        folder ??= Path.Combine(root, ".cache", "unicode", Version);
        var sums = File.ReadAllLines(Path.Combine(root, "tools", "Folio.Gen", $"unicode-{Version}.sha256"))
            .Where(l => l.Length > 0)
            .Select(l => l.Split("  ", 2))
            .ToDictionary(p => p[1], p => p[0], StringComparer.Ordinal);

        string Read(string relative)
        {
            var path = Path.Combine(folder, relative);
            if (!File.Exists(path))
                throw new FileNotFoundException($"{relative} is missing from {folder}.");
            var bytes = File.ReadAllBytes(path);
            var hash = Convert.ToHexStringLower(SHA256.HashData(bytes));
            if (hash != sums[relative])
                throw new InvalidDataException($"{relative} does not match its checksum in unicode-{Version}.sha256.");
            return Encoding.UTF8.GetString(bytes);
        }

        var lineBreak = Property(Read("LineBreak.txt"), null);
        var eastAsian = Property(Read("EastAsianWidth.txt"), null);
        var bidi = Property(Read("extracted/DerivedBidiClass.txt"), BidiShortNames);
        var word = Property(Read("auxiliary/WordBreakProperty.txt"), null);
        var script = Property(Read("Scripts.txt"), null);
        var emoji = Emoji(Read("emoji/emoji-data.txt"));
        var brackets = Pairs(Read("BidiBrackets.txt"), withType: true);
        var mirrors = Pairs(Read("BidiMirroring.txt"), withType: false);

        var code = new StringBuilder();
        code.Append($$"""
            // <auto-generated>
            // Generated by tools/Folio.Gen from the Unicode Character Database {{Version}}
            // (https://www.unicode.org/Public/{{Version}}/ucd/). Do not edit.
            // </auto-generated>

            namespace Folio.Typography;


            """);

        var lb = Enum(code, "LineBreakClass", "Line_Break (UAX #14)", lineBreak, "XX");
        var ea = Enum(code, "EastAsianWidth", "East_Asian_Width (UAX #11)", eastAsian, "N");
        var bc = Enum(code, "BidiClass", "Bidi_Class (UAX #9)", bidi, "L");
        var wb = Enum(code, "WordBreak", "Word_Break (UAX #29)", word, "Other");
        var sc = Enum(code, "Script", "Script (UAX #24)", script, "Unknown");
        code.Append("""
            /// <summary>Emoji properties (UTS #51).</summary>
            [Flags]
            internal enum EmojiProperties : byte
            {
                None = 0,
                Emoji = 1,
                EmojiPresentation = 2,
                EmojiModifier = 4,
                EmojiModifierBase = 8,
                EmojiComponent = 16,
                ExtendedPictographic = 32,
            }


            """);

        code.Append($$"""
            /// <summary>Character properties from the Unicode Character Database {{Version}}, as range tables.</summary>
            internal static partial class UnicodeData
            {
                public const string Version = "{{Version}}";

            """);
        Table(code, "LineBreak", "LineBreakClass", Values(lineBreak, lb));
        Table(code, "EastAsian", "EastAsianWidth", Values(eastAsian, ea));
        Table(code, "Bidi", "BidiClass", Values(bidi, bc));
        Table(code, "Word", "WordBreak", Values(word, wb));
        Table(code, "Scripts", "Script", Values(script, sc));
        Table(code, "Emoji", "EmojiProperties", emoji);
        Sorted(code, "BracketCodePoints", "int", brackets.Select(b => b.From.ToString("X", CultureInfo.InvariantCulture)).Select(h => "0x" + h));
        Sorted(code, "BracketPairs", "int", brackets.Select(b => "0x" + b.To.ToString("X", CultureInfo.InvariantCulture)));
        Sorted(code, "BracketIsOpen", "bool", brackets.Select(b => b.Open ? "true" : "false"));
        Sorted(code, "MirrorCodePoints", "int", mirrors.Select(b => "0x" + b.From.ToString("X", CultureInfo.InvariantCulture)));
        Sorted(code, "Mirrors", "int", mirrors.Select(b => "0x" + b.To.ToString("X", CultureInfo.InvariantCulture)));
        code.Append("}\n");

        var output = Path.Combine(root, "src", "Folio", "Typography", "UnicodeData.g.cs");
        await File.WriteAllTextAsync(output, code.ToString().ReplaceLineEndings("\n"));
        Console.WriteLine($"Unicode {Version} tables, {new FileInfo(output).Length / 1024} KiB -> {output}");
        return 0;
    }

    // One value per code point: the @missing defaults in order, then the listed ranges.
    private static string[] Property(string text, Dictionary<string, string>? aliases)
    {
        var values = new string[0x110000];
        foreach (var raw in text.Split('\n'))
        {
            var line = raw.Trim();
            var missing = line.StartsWith("# @missing:", StringComparison.Ordinal);
            if (missing)
                line = line["# @missing:".Length..];
            else if ((line = line.Split('#')[0].Trim()).Length == 0)
                continue;
            var fields = line.Split(';', StringSplitOptions.TrimEntries);
            var value = aliases?.GetValueOrDefault(fields[1]) ?? fields[1];
            var (first, last) = Range(fields[0]);
            for (var cp = first; cp <= last; cp++)
                values[cp] = value;
        }
        return values;
    }

    private static byte[] Emoji(string text)
    {
        var flags = new byte[0x110000];
        foreach (var raw in text.Split('\n'))
        {
            var line = raw.Split('#')[0].Trim();
            if (line.Length == 0)
                continue;
            var fields = line.Split(';', StringSplitOptions.TrimEntries);
            byte bit = fields[1] switch
            {
                "Emoji" => 1,
                "Emoji_Presentation" => 2,
                "Emoji_Modifier" => 4,
                "Emoji_Modifier_Base" => 8,
                "Emoji_Component" => 16,
                "Extended_Pictographic" => 32,
                _ => throw new InvalidDataException($"Unknown emoji property {fields[1]}."),
            };
            var (first, last) = Range(fields[0]);
            for (var cp = first; cp <= last; cp++)
                flags[cp] |= bit;
        }
        return flags;
    }

    private static List<(int From, int To, bool Open)> Pairs(string text, bool withType)
    {
        var pairs = new List<(int, int, bool)>();
        foreach (var raw in text.Split('\n'))
        {
            var line = raw.Split('#')[0].Trim();
            if (line.Length == 0)
                continue;
            var fields = line.Split(';', StringSplitOptions.TrimEntries);
            pairs.Add((Hex(fields[0]), Hex(fields[1]), withType && fields[2] == "o"));
        }
        return pairs.OrderBy(p => p.Item1).ToList();
    }

    private static (int First, int Last) Range(string field)
    {
        var parts = field.Split("..");
        return (Hex(parts[0]), Hex(parts[^1]));
    }

    private static int Hex(string text) => int.Parse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture);

    // Emits an enum of the values in use, the default first; returns name -> number.
    private static Dictionary<string, int> Enum(StringBuilder code, string name, string summary, string[] values, string first)
    {
        var names = values.Distinct().Where(v => v != first).Order(StringComparer.Ordinal).Prepend(first).ToList();
        code.Append($"/// <summary>{summary}.</summary>\ninternal enum {name} : byte\n{{\n");
        foreach (var n in names)
            code.Append($"    {n},\n");
        code.Append("}\n\n");
        return names.Select((n, i) => (n, i)).ToDictionary(x => x.n, x => x.i);
    }

    private static byte[] Values(string[] values, Dictionary<string, int> numbers) => values.Select(v => (byte)numbers[v]).ToArray();

    // A range table: the first code point of each run of equal values, and the runs' values.
    private static void Table(StringBuilder code, string name, string type, byte[] values)
    {
        var starts = new List<int> { 0 };
        for (var cp = 1; cp < values.Length; cp++)
        {
            if (values[cp] != values[cp - 1])
                starts.Add(cp);
        }
        code.Append($"\n    public static {type} {name}(int codePoint) => ({type})Lookup({name}Starts, {name}Values, codePoint);\n\n");
        Array(code, $"{name}Starts", "int", starts.Select(s => "0x" + s.ToString("X", CultureInfo.InvariantCulture)));
        Array(code, $"{name}Values", "byte", starts.Select(s => values[s].ToString(CultureInfo.InvariantCulture)));
    }

    private static void Sorted(StringBuilder code, string name, string type, IEnumerable<string> items)
    {
        code.Append('\n');
        Array(code, name, type, items);
    }

    private static void Array(StringBuilder code, string name, string type, IEnumerable<string> items)
    {
        code.Append($"    private static ReadOnlySpan<{type}> {name} =>\n    [\n");
        foreach (var chunk in items.Chunk(16))
            code.Append("        ").Append(string.Join(", ", chunk)).Append(",\n");
        code.Append("    ];\n");
    }

    // DerivedBidiClass.txt names its @missing values in full.
    private static readonly Dictionary<string, string> BidiShortNames = new(StringComparer.Ordinal)
    {
        ["Left_To_Right"] = "L", ["Right_To_Left"] = "R", ["Arabic_Letter"] = "AL", ["European_Terminator"] = "ET",
        ["Boundary_Neutral"] = "BN", ["Nonspacing_Mark"] = "NSM",
    };
}
