<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Folio.Tests" />
    <InternalsVisibleTo Include="Folio.RenderTests" />
    <InternalsVisibleTo Include="Folio.Fuzz" />
    <InternalsVisibleTo Include="Folio.Benchmarks" />
    <EmbeddedResource Include="Style\UserAgent.css" LogicalName="Folio.UserAgent.css" />
  </ItemGroup>

</Project>
