<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Folio\Folio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Html\**\*.txt;Css\**\*.txt;Style\**\*.txt;Layout\**\*.txt;Painting\**\*.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\fonts\*.ttf" LinkBase="fonts" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\images\*.png;..\images\*.jpg" LinkBase="images" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
